name: Deploy Frontend Kesiswaan

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        cd muallimin-ekskul-fe
        npm install

    - name: Generate .env File
      run: |
        cd muallimin-ekskul-fe
        echo "NEXT_PUBLIC_API_BACKEND_URL=${{ secrets.NEXT_PUBLIC_API_BACKEND_URL }}" > .env
        echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env
        echo "NEXT_PUBLIC_STORAGE_URL=${{ secrets.NEXT_PUBLIC_STORAGE_URL }}" >> .env

    - name: Build Next.js Application
      run: |
        cd muallimin-ekskul-fe
        npm run build

    - name: Transfer Files to Server (DirectAdmin)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "muallimin-ekskul-fe/.next,muallimin-ekskul-fe/public,muallimin-ekskul-fe/package.json,muallimin-ekskul-fe/next.config.ts"
        target: "/home/muallimi/domains/kesiswaan.muallimin.sch.id/public_html/"
        strip_components: 1 
        overwrite: true

    - name: Restart PM2 on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /home/muallimi/domains/kesiswaan.muallimin.sch.id/public_html/
          npm install --production
          pm2 restart frontend-kesiswaan
          pm2 save